# Generated by Django 6.0.6 on 2026-06-12 03:46

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_carbon_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'is_used', '-created_at'], name='accounts_em_user_id_7bddd4_idx'),
        ),
    ]
