# Generated by Django 6.0.6 on 2026-06-11 17:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transportation'), ('energy', 'Home Energy'), ('food', 'Food & Diet'), ('shopping', 'Shopping'), ('waste', 'Waste')], max_length=20)),
                ('sub_category', models.CharField(max_length=50)),
                ('factor', models.FloatField(help_text='kg CO2 per unit')),
                ('unit', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='EPA/DEFRA', max_length=200)),
            ],
            options={
                'ordering': ['category', 'sub_category'],
                'unique_together': {('category', 'sub_category')},
            },
        ),
        migrations.CreateModel(
            name='CarbonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transportation'), ('energy', 'Home Energy'), ('food', 'Food & Diet'), ('shopping', 'Shopping'), ('waste', 'Waste')], db_index=True, max_length=20)),
                ('sub_category', models.CharField(max_length=50)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=30)),
                ('carbon_kg', models.FloatField(help_text='Calculated CO2 in kg')),
                ('date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Carbon entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='calculator__user_id_e84fea_idx'), models.Index(fields=['user', 'category'], name='calculator__user_id_b4e247_idx')],
            },
        ),
    ]
