# Generated by Django 6.0.6 on 2026-06-12 03:46

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='carbon_save_potential',
            field=models.DecimalField(decimal_places=2, help_text='Estimated kg CO2 saved', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('transport', 'Transportation'), ('energy', 'Home Energy'), ('food', 'Food & Diet'), ('shopping', 'Shopping'), ('waste', 'Waste'), ('general', 'General')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='duration_days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userchallenge',
            index=models.Index(fields=['challenge', 'status'], name='challenges__challen_d3b7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallenge',
            index=models.Index(fields=['user', 'status'], name='challenges__user_id_407057_idx'),
        ),
    ]
